use_frameworks!

target 'libtest_Example' do
  pod 'libtest', :podspec => '../libtest.podspec'

  target 'libtest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
